;项目地址：https://github.com/Aethersailor/Custom_OpenClash_Rules
;本模板为Full模板改GFW

[custom]
;设置规则标志位
ruleset=国外,clash-classic:https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Proxy_Classical.yaml,28800
ruleset=国外,[]GEOSITE,category-communication
ruleset=国外,[]GEOSITE,category-social-media-!cn
ruleset=国外,[]GEOSITE,talkatone
ruleset=国外,[]GEOSITE,openai
ruleset=国外,[]GEOSITE,bing
ruleset=国外,[]GEOSITE,category-ai-!cn
ruleset=国外,[]GEOSITE,github
ruleset=国外,[]GEOSITE,youtube
ruleset=国外,[]GEOSITE,apple-tvplus
ruleset=国外,[]GEOSITE,googlefcm
ruleset=国外,[]GEOSITE,google
ruleset=国外,[]GEOSITE,tiktok
ruleset=国外,[]GEOSITE,netflix
ruleset=国外,[]GEOSITE,disney
ruleset=国外,[]GEOSITE,hbo
ruleset=国外,[]GEOSITE,primevideo
ruleset=国外,[]GEOSITE,category-emby
ruleset=国外,[]GEOSITE,spotify
ruleset=国外,[]GEOSITE,bahamut
ruleset=国外,[]GEOSITE,category-entertainment
ruleset=国外,[]GEOSITE,category-pt
ruleset=国外,[]GEOSITE,paypal
ruleset=国外,[]GEOSITE,category-ecommerce
ruleset=国外,[]GEOSITE,gfw
ruleset=国外,[]GEOIP,telegram,no-resolve
ruleset=国外,[]GEOIP,twitter,no-resolve
ruleset=国外,[]GEOIP,facebook,no-resolve
ruleset=国外,[]GEOIP,google,no-resolve
ruleset=国外,[]GEOIP,netflix,no-resolve
ruleset=其他,[]FINAL
;设置规则标志位结束

;设置节点分组标志位
custom_proxy_group=国外`select`[]美国节点`[]英国节点`[]德国节点`[]香港节点`[]日本节点`[]新加坡节点`[]♻️ 自动选择`[]🚀 手动选择`[]DIRECT
custom_proxy_group=其他`select`[]DIRECT`[]美国节点`[]英国节点`[]德国节点`[]香港节点`[]日本节点`[]新加坡节点`[]♻️ 自动选择`[]🚀 手动选择
custom_proxy_group=美国节点`url-test`(美|US|us|States)`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=英国节点`url-test`(英|UK|uk|Britain|Kingdom|England)`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=德国节点`url-test`(德|DE|de|Germany)`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=香港节点`url-test`(港|HK|hk|Hong Kong|HongKong|hongkong)`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=日本节点`url-test`(日本|JP|jp|Japan)`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=新加坡节点`url-test`(新加坡|狮城|SG|sg|Singapore)`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=♻️ 自动选择`url-test`.*`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🚀 手动选择`select`.*
;设置分组标志位

;下方参数请勿修改
enable_rule_generator=true
overwrite_original_rules=true
